### ISSUE TITLE
Error downloading `jpeg` & `pillow` with conda

### ISSUE THREAD

**Issue by vgunjal** [suvojit-0x55aa/celebA-HQ-dataset-download#2]
I get stuck at the same error whether I try the Docker approach or follow the instructions myself.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pillow==3.1.1
  - jpeg=8d
```

Am I doing something wrong? Or does the script need to be udpated?

**Comment by suvojit-0x55aa** [comment]
@vgunjal It needs a script update it seems. For now you can use [pre-built docker image](https://github.com/suvojit-0x55aa/celebA-HQ-dataset-download#prebuilt-docker-image), I'll update as soon as I can.

**Comment by vgunjal** [comment]
Okay. Thank you, I'll do that. 

If you would be so kind, can you please explain how the data is used here? Why do we generate multiple resolutions of the same image? How does that help in the training process?

**Comment by suvojit-0x55aa** [comment]
You can refer to Appendix C of [Progressive Growing of GANs paper](https://research.nvidia.com/sites/default/files/pubs/2017-10_Progressive-Growing-of/karras2018iclr-paper.pdf). It is implemented in the following line: https://github.com/suvojit-0x55aa/celebA-HQ-dataset-download/blob/23e78a0d2affb5447784c4a620f3dc976a5267fe/create_celeba_HQ.py#L174

If you have any other doubt feel free to ask.
