### ISSUE TITLE
Prebuilt Docker Image fails

### ISSUE THREAD

**Issue by gaseosaluz** [suvojit-0x55aa/celebA-HQ-dataset-download#3]
Per the instructions in the README, the command

`docker run -it -v $(pwd):/data suvojit0x55aa/celeba-hq`

Fails with:

`Loading CelebA data from /data/celebA
(202599, 5, 2)

Loading CelebA-HQ deltas from /data/celebA-HQ

Error: Expected to find 30 zips in /data/celebA-HQ/delta*.zip`

Any ideas as to what the problem may be?

**Comment by zplizzi** [comment]
Hm, works fine for me. Just ran it exactly as you described. Maybe a network error and one of the files failed to download?

**Comment by suvojit-0x55aa** [comment]
@gaseosaluz as @zplizzi said can you check if all the files are being downloaded ?
