### ISSUE TITLE
Can you share the 64x64 size data?

### ISSUE THREAD

**Issue by XinYu-Andy** [suvojit-0x55aa/celebA-HQ-dataset-download#7]
Hi, thanks for your effort!
It's very convenient to download the data directly from the google drive you shared.
I just note that it seems lack of the 64x64 size data version? Can you share this version?

**Comment by suvojit-0x55aa** [comment]
64x64 is just the normal celebA dataset, you can download it directly from [the main site](https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html)
